spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: never
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework.jdbc.core: DEBUG